title: Winter's Land
subtitle: 有朋自远方来，不亦乐乎
theme: winterland
author: winter
url: http://winterland.me
root: /

per_page: 10

archive_generator:
  per_page: 0

deploy:
  type: git
  repo: git@github.com:winterland1989/winterland1989.github.io.git
  branch: master
  message:

